meta_product_name: "Shareverything"
meta_title: "Shareverything - Send files easily"
meta_description: "Share large documents has never been so easy and fast. No need for registration. Send files to your friends or colleagues in one click. "
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@FlipoAlexis"   # required for Twitter Cards
twitter_account: "@prevost_jules"
